name: Mirror to Gitflic

on:
  push:
    branches: ['**']
  delete:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Push mirror to Gitflic
        run: |
          git push --mirror \
            "https://shkrndns:${{ secrets.GITFLIC_TOKEN }}@gitflic.ru/project/shkrndns/white_anrotrip.git"
